version: "3.3"
services:
  cryptohttp:
    container_name: cryptohttp
    environment:
      PORT: 8080
    image: cryptohttp
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /config:/app/config
